
services:
  eft-helper-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eft-helper-bot
    restart: unless-stopped
    
    # Переменные окружения из .env файла
    env_file:
      - .env
    
    # Том для сохранения базы данных
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Ограничения ресурсов (опционально)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Политика перезапуска
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Healthcheck (опционально)
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/eft_helper.db') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
