
services:
  # Ollama AI Service (v5.1)
  # ЗАКОММЕНТИРОВАНО: используется локально установленный Ollama
  # Раскомментируйте, если хотите запустить Ollama в Docker
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: eft-helper-ollama
  #   restart: unless-stopped
  #   
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   
  #   ports:
  #     - "11434:11434"
  #   
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '4.0'
  #         memory: 8G
  #       reservations:
  #         cpus: '2.0'
  #         memory: 4G
  #   
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 60s

  # EFT Helper Bot
  eft-helper-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eft-helper-bot
    restart: unless-stopped
    
    # Переменные окружения из .env файла
    env_file:
      - .env
    
    # Дополнительные переменные (при необходимости переопределения)
    # environment:
    #   - OLLAMA_URL=http://host.docker.internal:11434
    
    # Том для сохранения базы данных
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    
    # Зависимости закомментированы - используется локальный Ollama
    # depends_on:
    #   ollama:
    #     condition: service_healthy
    
    # Ограничения ресурсов (опционально)
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    
    # Политика перезапуска
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Healthcheck (опционально)
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/eft_helper.db') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Закомментировано - используется локальный Ollama
# volumes:
#   ollama_data:
