"""Localization texts for the EFT Helper bot."""

TEXTS = {
    "ru": {
        # Main menu
        "main_menu": "🏠 Главное меню",
        "search_weapon": "🔍 Поиск оружия",
        "all_quest_builds": "📜 Все квестовые сборки",
        "random_build": "🎲 Случайная сборка",
        "meta_builds": "⚔️ Мета-сборки",
        "loyalty_builds": "🤝 Сборки по лояльности торговцев",
        "best_weapons": "⭐ Лучшее оружие",
        "settings": "⚙️ Настройки",
        
        # Welcome message
        "welcome": "👋 Добро пожаловать в EFT Helper!\n\nЭтот бот поможет вам подобрать оптимальные сборки оружия для Escape from Tarkov.\n\nВыберите действие из меню ниже:",
        "select_language": "🌍 Выберите язык / Select your language:",
        "language_selected": "✅ Язык выбран: Русский\n\nДобро пожаловать в EFT Helper! Этот бот поможет вам подобрать оптимальные сборки оружия для Escape from Tarkov.",
        
        # Search
        "enter_weapon_name": "🔍 Введите название оружия для поиска:\n\nНапример: AK-74N, MP-153, M4A1",
        "weapon_not_found": "❌ Оружие не найдено. Попробуйте другой запрос.",
        "select_weapon": "Выберите оружие:",
        "no_weapons_found": "❌ Оружие не найдено в базе данных.",
        
        # Build filters
        "select_build_type": "Выберите тип сборки для {weapon}:",
        "random_build_btn": "🎲 Случайная",
        "meta_build_btn": "⚔️ Мета",
        "quest_build_btn": "📜 Квестовая",
        "constructor_btn": "🛠️ Конфигуратор",
        "budget_build_btn": "💰 По бюджету",
        "loyalty_build_btn": "🤝 По лояльности",
        
        # Build display
        "build_card_title": "🔫 {weapon}\n",
        "build_category": "📂 Категория: {category}",
        "build_quest": "📜 Квест: {quest}",
        "build_modules": "🔧 Модули:",
        "build_total_cost": "💰 Общая стоимость: {cost} ₽",
        "build_loyalty": "🤝 Минимальная лояльность: {level}",
        "build_planner": "🔗 [Открыть в планировщике]({link})",
        "no_builds_found": "❌ Сборки не найдены для этого оружия.",
        
        # Quest builds
        "quest_builds_list": "📜 Квестовые сборки\n\nВыберите квест:",
        "no_quest_builds": "❌ Квестовые сборки не найдены.",
        "quest_description": "📝 {description}",
        "loading_quests": "⏳ Загружаю квесты...",
        "quest_builds_title": "📜 Квестовые сборки",
        "all_quest_builds_title": "📜 Все квестовые сборки",
        "select_quest": "Выберите квест для просмотра информации:",
        "quest_trader": "Торговец",
        "quest_level": "Требуемый уровень",
        "quest_experience": "Опыт",
        "quest_map": "Карта",
        "quest_required_tasks": "Требуемые квесты",
        "quest_objectives": "Цели",
        "quest_optional": "опц.",
        "quest_and_more": "и ещё",
        "quest_more_objectives": "целей",
        "quest_recommended_build": "Рекомендуемая сборка",
        
        # Random build
        "random_build_title": "🎲 Случайная сборка",
        "generating_random": "🎲 Генерирую случайную сборку...",
        "truly_random_build": "🎰 Рандомная сборка",
        "generating_truly_random": "🎰 Генерирую по-настоящему рандомную сборку...",
        "truly_random_build_title": "🎰 Рандомная сборка",
        
        # Meta builds
        "meta_builds_title": "⚔️ Мета-сборки 2025",
        "meta_builds_desc": "Актуальные топовые сборки по категориям:",
        "no_meta_builds": "❌ Мета-сборки не найдены.",
        
        # Loyalty builds
        "select_trader": "🤝 Выберите торговца:",
        "select_loyalty_level": "Выберите уровень лояльности для {trader}:",
        "loyalty_level": "Уровень {level}",
        "no_loyalty_builds": "❌ Нет доступных сборок для {trader} (уровень {level}).",
        "setup_loyalty_levels": "🤝 Настройка уровней лояльности\n\nУкажите ваши текущие уровни лояльности к торговцам. Это позволит боту показывать только доступные вам сборки.",
        "current_loyalty_levels": "Текущие уровни лояльности:",
        "trader_level_set": "✅ Уровень лояльности к {trader} установлен: {level}",
        "loyalty_levels_saved": "✅ Уровни лояльности сохранены!",
        "show_available_builds": "📋 Показать доступные сборки",
        "reset_loyalty_levels": "🔄 Сбросить уровни",
        "select_weapon_category": "Выберите категорию оружия:",
        "any_category": "🔫 Любая категория",
        "enter_max_budget": "💰 Введите максимальный бюджет (в рублях):\n\nНапример: 500000\n\nОтправьте /skip чтобы пропустить",
        "skip_budget": "⏭️ Пропустить бюджет",
        "invalid_budget_format": "❌ Неверный формат. Введите число или /skip",
        "budget_set_to": "✅ Бюджет установлен: {budget} ₽",
        "no_budget_limit": "♾️ Без ограничения бюджета",
        "loyalty_builds_filters": "📋 Фильтры:\n  • Категория: {category}\n  • Бюджет: {budget}",
        "found_builds": "Найдено сборок: {count}",
        "regenerate": "🔄 Перегенерировать",
        
        # Best weapons
        "best_weapons_title": "⭐ Лучшее оружие по категориям",
        "tier_s": "🏆 S-Tier (Лучшие)",
        "tier_a": "🥇 A-Tier (Отличные)",
        "tier_b": "🥈 B-Tier (Хорошие)",
        "tier_c": "🥉 C-Tier (Средние)",
        "tier_d": "📊 D-Tier (Слабые)",
        "no_tier_weapons": "❌ Оружие не найдено для этого уровня.",
        
        # Settings
        "settings_title": "⚙️ Настройки",
        "current_language": "Текущий язык: {language_name}",
        "change_language": "Изменить язык:",
        "language_changed": "✅ Язык изменен на: {language_name}",
        "lang_ru": "🇷🇺 Русский",
        "lang_en": "🇬🇧 English",
        
        # Build Constructor (v3.0)
        "build_constructor": "🛠 Конструктор сборок",
        "dynamic_random_build": "🎲 Динамическая сборка",
        "community_builds": "👥 Сборки сообщества",
        "my_builds": "💾 Мои сборки",
        "constructor_title": "🛠 Конструктор сборок",
        "constructor_desc": "Создайте свою идеальную сборку с учётом бюджета и лояльности",
        "select_weapon_for_build": "Выберите оружие для сборки:",
        "enter_budget": "💰 Введите бюджет в рублях (например: 150000):",
        "budget_set": "✅ Бюджет установлен: {budget} ₽",
        "invalid_budget": "❌ Неверный формат бюджета. Введите число.",
        "use_flea_market": "🛒 Использовать только Flea Market?",
        "generating_build": "⚙️ Генерирую сборку...",
        "build_generated": "✅ Сборка сгенерирована!",
        "save_build": "💾 Сохранить",
        "regenerate_build": "🔄 Перегенерировать",
        "share_build": "📤 Поделиться",
        "build_saved": "✅ Сборка сохранена!",
        "enter_build_name": "Введите название сборки:",
        "build_stats": "📊 Характеристики:",
        "build_ergonomics": "  • Эргономика: {value}",
        "build_recoil_v": "  • Вертикальная отдача: {value}",
        "build_recoil_h": "  • Горизонтальная отдача: {value}",
        "build_tier": "🏆 Тир качества: {tier}",
        "build_spent": "💸 Потрачено: {cost} ₽ из {budget} ₽",
        "build_remaining": "💰 Остаток: {remaining} ₽",
        "build_available_from": "🛒 Доступно: {sources}",
        "build_modules_list": "🔧 Модули:",
        
        # Community Builds
        "community_builds_title": "👥 Сборки сообщества",
        "community_builds_desc": "Просмотр и копирование сборок других игроков",
        "no_community_builds": "❌ Пока нет публичных сборок",
        "build_by_user": "Автор: Пользователь #{user_id}",
        "build_likes": "👍 {count}",
        "like_build": "👍 Нравится",
        "copy_build": "📋 Копировать",
        "build_copied": "✅ Сборка скопирована в ваши сохранения!",
        "build_liked": "✅ Вам понравилась эта сборка!",
        "view_details": "📝 Детали",
        "make_public": "🌐 Опубликовать",
        "make_private": "🔒 Скрыть",
        "build_published": "✅ Сборка опубликована!",
        "build_unpublished": "✅ Сборка скрыта",
        "delete_build": "🗑 Удалить",
        "build_deleted": "✅ Сборка удалена",
        "confirm_delete": "Вы уверены, что хотите удалить эту сборку?",
        "my_builds_title": "💾 Мои сборки",
        "no_saved_builds": "❌ У вас пока нет сохранённых сборок",
        
        # Dynamic Build Generation
        "dynamic_build_title": "🎲 Динамическая сборка",
        "dynamic_build_desc": "Генерация случайной сборки с учётом ваших параметров",
        "setup_generation": "⚙️ Настройка генерации",
        "any_weapon": "Любое оружие",
        "budget_question": "Какой у вас бюджет?",
        "flea_only_question": "Использовать только Flea Market?",
        "yes": "✅ Да",
        "no": "❌ Нет",
        "prioritize_question": "Что приоритезировать?",
        "prioritize_ergo": "📈 Эргономика",
        "prioritize_recoil": "📉 Отдача",
        "balanced": "⚖️ Баланс",
        
        # Traders
        "prapor": "Прапор",
        "therapist": "Терапевт",
        "fence": "Скупщик",
        "skier": "Лыжник",
        "peacekeeper": "Миротворец",
        "mechanic": "Механик",
        "ragman": "Барахольщик",
        "jaeger": "Егерь",
        "lightkeeper": "Смотритель",
        # Trader names mapping (for API responses)
        "trader_prapor": "Прапор",
        "trader_therapist": "Терапевт",
        "trader_fence": "Скупщик",
        "trader_skier": "Лыжник",
        "trader_peacekeeper": "Миротворец",
        "trader_mechanic": "Механик",
        "trader_ragman": "Барахольщик",
        "trader_jaeger": "Егерь",
        "trader_lightkeeper": "Смотритель",
        
        # Categories
        "assault_rifle": "Штурмовая винтовка",
        "smg": "Пистолет-пулемет",
        "sniper": "Снайперская винтовка",
        "dmr": "Марксманская винтовка",
        "shotgun": "Дробовик",
        "pistol": "Пистолет",
        "lmg": "Ручной пулемет",
        
        # Build categories
        "category_random": "Случайная",
        "category_meta": "Мета",
        "category_quest": "Квестовая",
        "category_loyalty": "По лояльности",
        
        # Weapon categories
        "select_category": "Выберите категорию оружия:",
        "category_pistols": "🔫 Пистолеты",
        "category_smg": "🔫 Пистолеты-пулемёты",
        "category_assault_rifles": "🔫 Штурмовые винтовки",
        "category_dmr": "🔫 Марксманские винтовки",
        "category_sniper_rifles": "🔫 Снайперские винтовки",
        "category_shotguns": "🔫 Дробовики",
        "category_lmg": "🔫 Пулемёты",
        "search_by_name": "🔍 Поиск по названию",
        
        # Weapon stats
        "caliber": "Калибр",
        "fire_rate": "Скорострельность",
        "weapon_price": "Цена оружия",
        "weapon_characteristics": "ХАРАКТЕРИСТИКИ ОРУЖИЯ",
        "final_stats": "ИТОГОВЫЕ ХАРАКТЕРИСТИКИ",
        "ergonomics_stat": "Эргономика",
        "vertical_recoil": "Вертикальная отдача",
        "horizontal_recoil": "Горизонтальная отдача",
        "budget_title": "БЮДЖЕТ",
        "spent": "Потрачено",
        "remaining": "Остаток",
        
        # Media types
        "media_photo": "фото",
        "media_video": "видео",
        "media_document": "документ",
        
        # Common
        "back": "◀️ Назад",
        "main_menu_btn": "🏠 Главное меню",
        "error": "❌ Произошла ошибка. Попробуйте снова.",
    },
    "en": {
        # Main menu
        "main_menu": "🏠 Main Menu",
        "search_weapon": "🔍 Search Weapon",
        "all_quest_builds": "📜 All Quest Builds",
        "random_build": "🎲 Random Build",
        "meta_builds": "⚔️ Meta Builds",
        "loyalty_builds": "🤝 Loyalty Builds",
        "best_weapons": "⭐ Best Weapons",
        "settings": "⚙️ Settings",
        
        # Welcome message
        "welcome": "👋 Welcome to EFT Helper!\n\nThis bot will help you find optimal weapon builds for Escape from Tarkov.\n\nChoose an action from the menu below:",
        "select_language": "🌍 Выберите язык / Select your language:",
        "language_selected": "✅ Language selected: English\n\nWelcome to EFT Helper! This bot will help you find optimal weapon builds for Escape from Tarkov.",
        
        # Search
        "enter_weapon_name": "🔍 Enter weapon name to search:\n\nFor example: AK-74N, MP-153, M4A1",
        "weapon_not_found": "❌ Weapon not found. Try another query.",
        "select_weapon": "Select weapon:",
        "no_weapons_found": "❌ No weapons found in database.",
        
        # Build filters
        "select_build_type": "Select build type for {weapon}:",
        "random_build_btn": "🎲 Random",
        "meta_build_btn": "⚔️ Meta",
        "quest_build_btn": "📜 Quest",
        "constructor_btn": "🛠️ Constructor",
        "budget_build_btn": "💰 By Budget",
        "loyalty_build_btn": "🤝 By Loyalty",
        
        # Build display
        "build_card_title": "🔫 {weapon}\n",
        "build_category": "📂 Category: {category}",
        "build_quest": "📜 Quest: {quest}",
        "build_modules": "🔧 Modules:",
        "build_total_cost": "💰 Total Cost: {cost} ₽",
        "build_loyalty": "🤝 Minimum Loyalty: {level}",
        "build_planner": "🔗 [Open in Planner]({link})",
        "no_builds_found": "❌ No builds found for this weapon.",
        
        # Quest builds
        "quest_builds_list": "📜 Quest Builds\n\nSelect a quest:",
        "no_quest_builds": "❌ No quest builds found.",
        "quest_description": "📝 {description}",
        "loading_quests": "⏳ Loading quests...",
        "quest_builds_title": "📜 Quest Builds",
        "all_quest_builds_title": "📜 All Quest Builds",
        "select_quest": "Select a quest to view information:",
        "quest_trader": "Trader",
        "quest_level": "Required Level",
        "quest_experience": "Experience",
        "quest_map": "Map",
        "quest_required_tasks": "Required Tasks",
        "quest_objectives": "Objectives",
        "quest_optional": "opt.",
        "quest_and_more": "and",
        "quest_more_objectives": "more objectives",
        "quest_recommended_build": "Recommended Build",
        
        # Random build
        "random_build_title": "🎲 Random Build",
        "generating_random": "🎲 Generating random build...",
        "truly_random_build": "🎰 True Random Build",
        "generating_truly_random": "🎰 Generating truly random build...",
        "truly_random_build_title": "🎰 True Random Build",
        
        # Meta builds
        "meta_builds_title": "⚔️ Meta Builds 2025",
        "meta_builds_desc": "Current top builds by category:",
        "no_meta_builds": "❌ No meta builds found.",
        
        # Loyalty builds
        "select_trader": "🤝 Select a trader:",
        "select_loyalty_level": "Select loyalty level for {trader}:",
        "loyalty_level": "Level {level}",
        "no_loyalty_builds": "❌ No available builds for {trader} (level {level}).",
        "setup_loyalty_levels": "🤝 Loyalty Levels Setup\n\nSet your current trader loyalty levels. This will allow the bot to show only builds available to you.",
        "current_loyalty_levels": "Current loyalty levels:",
        "trader_level_set": "✅ Loyalty level for {trader} set to: {level}",
        "loyalty_levels_saved": "✅ Loyalty levels saved!",
        "show_available_builds": "📋 Show Available Builds",
        "reset_loyalty_levels": "🔄 Reset Levels",
        "select_weapon_category": "Select weapon category:",
        "any_category": "🔫 Any Category",
        "enter_max_budget": "💰 Enter maximum budget (in rubles):\n\nFor example: 500000\n\nSend /skip to skip",
        "skip_budget": "⏭️ Skip Budget",
        "invalid_budget_format": "❌ Invalid format. Enter a number or /skip",
        "budget_set_to": "✅ Budget set to: {budget} ₽",
        "no_budget_limit": "♾️ No budget limit",
        "loyalty_builds_filters": "📋 Filters:\n  • Category: {category}\n  • Budget: {budget}",
        "found_builds": "Found {count} builds",
        "regenerate": "🔄 Regenerate",
        
        # Best weapons
        "best_weapons_title": "⭐ Best Weapons by Category",
        "tier_s": "🏆 S-Tier (Best)",
        "tier_a": "🥇 A-Tier (Excellent)",
        "tier_b": "🥈 B-Tier (Good)",
        "tier_c": "🥉 C-Tier (Average)",
        "tier_d": "📊 D-Tier (Weak)",
        "no_tier_weapons": "❌ No weapons found for this tier.",
        
        # Settings
        "settings_title": "⚙️ Settings",
        "current_language": "Current language: {language_name}",
        "change_language": "Change language:",
        "language_changed": "✅ Language changed to: {language_name}",
        "lang_ru": "🇷🇺 Русский",
        "lang_en": "🇬🇧 English",
        
        # Build Constructor (v3.0)
        "build_constructor": "🛠 Build Constructor",
        "dynamic_random_build": "🎲 Dynamic Build",
        "community_builds": "👥 Community Builds",
        "my_builds": "💾 My Builds",
        "constructor_title": "🛠 Build Constructor",
        "constructor_desc": "Create your perfect build with budget and loyalty constraints",
        "select_weapon_for_build": "Select weapon for build:",
        "enter_budget": "💰 Enter budget in rubles (e.g., 150000):",
        "budget_set": "✅ Budget set: {budget} ₽",
        "invalid_budget": "❌ Invalid budget format. Enter a number.",
        "use_flea_market": "🛒 Use Flea Market only?",
        "generating_build": "⚙️ Generating build...",
        "build_generated": "✅ Build generated!",
        "save_build": "💾 Save",
        "regenerate_build": "🔄 Regenerate",
        "share_build": "📤 Share",
        "build_saved": "✅ Build saved!",
        "enter_build_name": "Enter build name:",
        "build_stats": "📊 Stats:",
        "build_ergonomics": "  • Ergonomics: {value}",
        "build_recoil_v": "  • Vertical Recoil: {value}",
        "build_recoil_h": "  • Horizontal Recoil: {value}",
        "build_tier": "🏆 Quality Tier: {tier}",
        "build_spent": "💸 Spent: {cost} ₽ of {budget} ₽",
        "build_remaining": "💰 Remaining: {remaining} ₽",
        "build_available_from": "🛒 Available: {sources}",
        "build_modules_list": "🔧 Modules:",
        
        # Community Builds
        "community_builds_title": "👥 Community Builds",
        "community_builds_desc": "View and copy builds from other players",
        "no_community_builds": "❌ No public builds yet",
        "build_by_user": "Author: User #{user_id}",
        "build_likes": "👍 {count}",
        "like_build": "👍 Like",
        "copy_build": "📋 Copy",
        "build_copied": "✅ Build copied to your saves!",
        "build_liked": "✅ You liked this build!",
        "view_details": "📝 Details",
        "make_public": "🌐 Publish",
        "make_private": "🔒 Hide",
        "build_published": "✅ Build published!",
        "build_unpublished": "✅ Build hidden",
        "delete_build": "🗑 Delete",
        "build_deleted": "✅ Build deleted",
        "confirm_delete": "Are you sure you want to delete this build?",
        "my_builds_title": "💾 My Builds",
        "no_saved_builds": "❌ You don't have any saved builds yet",
        
        # Dynamic Build Generation
        "dynamic_build_title": "🎲 Dynamic Build",
        "dynamic_build_desc": "Generate random build with your parameters",
        "setup_generation": "⚙️ Setup Generation",
        "any_weapon": "Any Weapon",
        "budget_question": "What's your budget?",
        "flea_only_question": "Use Flea Market only?",
        "yes": "✅ Yes",
        "no": "❌ No",
        "prioritize_question": "What to prioritize?",
        "prioritize_ergo": "📈 Ergonomics",
        "prioritize_recoil": "📉 Recoil",
        "balanced": "⚖️ Balanced",
        
        # Traders
        "prapor": "Prapor",
        "therapist": "Therapist",
        "fence": "Fence",
        "skier": "Skier",
        "peacekeeper": "Peacekeeper",
        "mechanic": "Mechanic",
        "ragman": "Ragman",
        "jaeger": "Jaeger",
        "lightkeeper": "Lightkeeper",
        # Trader names mapping (for API responses)
        "trader_prapor": "Prapor",
        "trader_therapist": "Therapist",
        "trader_fence": "Fence",
        "trader_skier": "Skier",
        "trader_peacekeeper": "Peacekeeper",
        "trader_mechanic": "Mechanic",
        "trader_ragman": "Ragman",
        "trader_jaeger": "Jaeger",
        "trader_lightkeeper": "Lightkeeper",
        
        # Categories
        "assault_rifle": "Assault Rifle",
        "smg": "Submachine Gun",
        "sniper": "Sniper Rifle",
        "dmr": "Designated Marksman Rifle",
        "shotgun": "Shotgun",
        "pistol": "Pistol",
        "lmg": "Light Machine Gun",
        
        # Build categories
        "category_random": "Random",
        "category_meta": "Meta",
        "category_quest": "Quest",
        "category_loyalty": "By Loyalty",
        
        # Weapon categories
        "select_category": "Select weapon category:",
        "category_pistols": "🔫 Pistols",
        "category_smg": "🔫 Submachine Guns",
        "category_assault_rifles": "🔫 Assault Rifles",
        "category_dmr": "🔫 Marksman Rifles",
        "category_sniper_rifles": "🔫 Sniper Rifles",
        "category_shotguns": "🔫 Shotguns",
        "category_lmg": "🔫 Machine Guns",
        "search_by_name": "🔍 Search by Name",
        
        # Weapon stats
        "caliber": "Caliber",
        "fire_rate": "Fire Rate",
        "weapon_price": "Weapon Price",
        "weapon_characteristics": "WEAPON CHARACTERISTICS",
        "final_stats": "FINAL STATS",
        "ergonomics_stat": "Ergonomics",
        "vertical_recoil": "Vertical Recoil",
        "horizontal_recoil": "Horizontal Recoil",
        "budget_title": "BUDGET",
        "spent": "Spent",
        "remaining": "Remaining",
        
        # Media types
        "media_photo": "photo",
        "media_video": "video",
        "media_document": "document",
        
        # Common
        "back": "◀️ Back",
        "main_menu_btn": "🏠 Main Menu",
        "error": "❌ An error occurred. Please try again.",
    }
}


def get_text(key: str, language: str = "ru", **kwargs) -> str:
    """Get localized text by key."""
    text = TEXTS.get(language, TEXTS["ru"]).get(key, key)
    if kwargs:
        return text.format(**kwargs)
    return text
